### DISCUSSION TITLE
Start compiling

### DISCUSSION THREAD

**Discussion by Banaanae** [mmikeww/AHK-v2-script-converter#212] [Ideas]
We could start compiling the script to have a "it just works" binary, without the bulky test suite. Would this be useful to anyone.

For preventing errors: We can use the `A_IsCompiled` var to check the program is compiled and display a message box to let them know (eg when the user turns on testmode)

**Comment by Banaanae** [comment]
^ Should add we can then publish under releases

**Reply by Banaanae** [reply]
Been testing with GitHub actions, I can compile successfully, but I haven't figured out how to then release the binary, no point automatically compiling if I still need to find download and release the binary manually

**Reply by fade2gray** [reply]
The release should come with a warning that Windows 'Reputation-based protection' needs dropping in order to use - it silently fails otherwise.

**Reply by Banaanae** [reply]
I added this in v1.0.3

**Comment by andymbody** [comment]
Clarification... You are referring to providing a lightweight binary (exe) as an alternative for "users" to download, instead of them being required to download the entire project (which includes the bulky test suite)? It probably sounds like I just repeated what you said, but I am checking my understanding of your statement?

**Reply by Banaanae** [reply]
Exactly correct
Could even add auto update checking, or maybe not (I don't want the project to get too bloated)

**Reply by andymbody** [reply]
ok... I never really thought about it until you mentioned this, but you may be right about scaling it down for the general user. The project folder is a little much and confused me when I first started to use the tool, so a lightweight alternative might be much better.

**Comment by Banaanae** [comment]
```yml
name: Build Binary and release

on: # Only run when a release is created
  push:
    tags:
      - '*'

jobs:
  BuildAndRelease:
    name: Build and Release
    runs-on: windows-latest
    steps:
      - name: Checkout # Get repository
        uses: actions/checkout@v2

      - name: Ahk2Exe # Build binary
        id: ahk2exe
        uses: CCCC-L/Action-Ahk2Exe@main
        with:
          in: script.ahk
          
      - name: Release # Upload binary to most recent release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GH_RELEASE }}
          files: script.exe
```
Here is a github actions script that automatically builds and uploads the script when a release is created
@mmikeww Unfortunately using `secrets.GITHUB_TOKEN` just would not work, despite what all the actions said, so instead this would require you to
1. Create a GitHub Personal Access Token (only tested with classic) with the repo scope and no expiry
2. Save that token as a repository secret under the name `GH_RELEASE`
